# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gJ8PZCwatVwZQjc2gto3RwwdPSBQrJPF
"""

teste

